### ISSUE TITLE
Small merge conflict since linux 4.18-rc6

### ISSUE THREAD

**Issue by Mdyrl7777777** [smeso/sara#3]
One of the commits for linux 4.18-rc6 introduced [small merge conflict](https://github.com/torvalds/linux/commit/3928d4f5ee37cdc523894f6e549e6aae521d8980#diff-fdaaedaf96a6a572e21218cb5e8691d9L3353) with SARA. Below is a fix:

```
@@ -947,7 +947,7 @@
 +	if (ret)
 +		return ERR_PTR(ret);
 +
- 	vma = kmem_cache_zalloc(vm_area_cachep, GFP_KERNEL);
+ 	vma = vm_area_alloc(mm);
  	if (unlikely(vma == NULL))
  		return ERR_PTR(-ENOMEM);
 diff -uprN --ignore-space-change linux-4.17.1/security/Kconfig linux-4.17.1b/security/Kconfig

```

**Comment by smeso** [comment]
Thank you for reporting. It should be fixed now. :)
